# Create draft PR releases on pull requests to develop

name: PR Release

on:
  pull_request:
    branches:
      - develop

jobs:
  build-for-pr-release:
    steps:
      - uses: ./.github/workflows/_release.yml
        with:
          version: latest

  upload-pr-release:
    needs: [build-for-pr-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          path: |
            fastfec-linux-x86_64-latest.zip
            libfastfec-linux-x86_64-latest.so
            fastfec-linux-aarch64-latest.zip
            libfastfec-linux-aarch64-latest.so
            fastfec-macos-x86_64-latest.zip
            libfastfec-macos-x86_64-latest.dylib
            fastfec-macos-aarch64-latest.zip
            libfastfec-macos-aarch64-latest.dylib
            fastfec-windows-x86_64-latest.zip
            libfastfec-windows-x86_64-latest.dll
            fastfec-windows-aarch64-latest.zip
            libfastfec-windows-aarch64-latest.dll
            libfastfec-latest.wasm

  build-wheels-for-pr-release:
    uses: ./.github/workflows/_python-wheels.yml
